import onnxruntime as ort
import numpy as np
import cv2

onnx_model_path = "onnx-inference-app/onnxmodels/attribute.onnx"  # Replace with your model path
image_path = "/Users/ties/Pictures/sweater5.jpg"        # Replace with your image path

ATTRIBUTE_LIST_COARSE = [
'a-line',
'abstract',
'abstract chevron',
'abstract chevron print',
'abstract diamond',
'abstract floral',
'abstract floral print',
'abstract geo',
'abstract geo print',
'abstract paisley',
'abstract pattern',
'abstract print',
'abstract printed',
'abstract stripe',
'acid',
'acid wash',
'americana',
'angeles',
'animal',
'animal print',
'ankle',
'applique',
'arrow collar',
'art',
'asymmetric',
'asymmetrical',
'asymmetrical hem',
'athletic',
'audrey',
'babe',
'babydoll',
'back bow',
'back cutout',
'back knit',
'back lace',
'back striped',
'backless',
'baja',
'bandage',
'bandana',
'bandana print',
'barbie',
'baroque',
'baroque print',
'baseball',
'basic',
'basquiat',
'batwing',
'beach',
'bead',
'beaded',
'beaded chiffon',
'beaded collar',
'beaded sheer',
'beaded shift',
'beatles',
'bed',
'bejeweled',
'bell',
'bell-sleeve',
'bella',
'belted',
'belted chiffon',
'belted floral',
'belted floral print',
'belted lace',
'belted maxi',
'belted plaid',
'bermuda',
'bib',
'big',
'bike',
'biker',
'bird',
'bird print',
'blah',
'bleach',
'bleached',
'bleached denim',
'blurred',
'boat neck',
'bodycon',
'bodycon midi',
'boho',
'bold',
'botanical',
'botanical print',
'bow',
'bow-back',
'bow-front',
'box',
'box pleat',
'box-pleated',
'boxy',
'boxy crop',
'boxy knit',
'boxy lace',
'boxy pocket',
'boxy striped',
'boyfriend',
'braided',
'breton',
'breton stripe',
'brocade',
'brooklyn',
'brooklyn nets',
'brushstroke',
'brushstroke print',
'burnout',
'bustier',
'butterfly',
'butterfly print',
'button',
'button-front',
'buttoned',
'cable',
'cable knit',
'cable-knit',
'caged',
'california',
'camera',
'cami',
'cami crop',
'cami maxi',
'camo',
'camouflage',
'candy',
'canvas',
'cap-sleeve',
'capri',
'cardio',
'cargo',
'cat',
'chambray',
'chambray drawstring',
'checked',
'checkered',
'cheetah',
'chenille',                     
'chevron',
'chevron print',
'chic',
'chiffon',   
'chiffon floral',
'chiffon lace',
'chiffon layered',
'chiffon maxi',
'chiffon paneled',  
'chiffon pleated',
'chiffon shift',
'chiffon shirt',
'chiffon surplice',
'chiffon-paneled',
'chino',
'chunky',
'chunky knit',
'cinched',
'circle',
'cities',
'city',
'civil',
'clashist',
'classic',
'classic cotton',
'classic crew',
'classic crew neck',
'classic denim',
'classic fit',
'classic knit',
'classic pocket',
'classic skinny',
'classic striped',
'classic v-neck',
'classic woven',
'clean',
'clean wash',
'cloud',
'cloud wash',
'coast',
'coated',                       
'coffee',
'collar',
'collar lace',
'collared',
'collarless',
'collarless faux',
'colorblock',
'colorblock pocket',
'colorblocked',
'combo',
'combo maxi',
'contrast',
'contrast trim',
'contrast-trimmed',
'convertible',
'corduroy',
'cotton',
'cotton drawstring',
'cotton knit',
'cotton-blend',
'cover-up',
'cowl',
'cowl neck',
'cozy',
'crepe',
'crepe shift',
'crepe woven',
'crew',
'crew neck',
'crinkled',
'crisscross',
'crisscross-back',
'crochet',
'crochet crop',
'crochet embroidered',
'crochet floral',
'crochet fringe',
'crochet knit',
'crochet lace',
'crochet maxi',
'crochet mesh',
'crochet overlay',
'crochet-paneled',
'crochet-trimmed',
'crocheted',
'crocheted lace',
'crop',
'cropped',
'cropped knit',
'cross-back',
'crossback',
'cuffed',
'cuffed denim',
'cuffed-sleeve',
'curved',
'curved hem',
'cut',
'cute',
'cutoff',
'cutout',
'cutout lace',
'cutout maxi',
'cutout sheath',
'cutout-back',
'dainty',
'daisy',
'daisy print',
'damask',       
'daring',
'dark',       
'darling',
'deep v-neck',
'deep-v',
'defyant',
'denim',
'denim drawstring',
'denim pencil',
'denim shift',             
'denim shirt',
'denim skater',        
'denim utility',
'desert',
'destroyed',
'devil',
'diamond',
'diamond print',
'dip-dye',
'dip-dyed',
'distressed',
'distressed low-rise',
'distressed mid-rise',
'distressed skinny',
'ditsy',
'ditsy floral',
'ditsy floral print',
'doll',
'dolman',
'dolman sleeve',
'dolman-sleeve',
'dolphin',
'dolphin hem',
'doodle',
'dot',
'dots',
'dotted',
'double-breasted',
'drape-front',
'draped',
'draped open-front',
'draped shawl',
'draped surplice',
'drapey',
'drawstring',
'dream',
'dreamcatcher',
'dreamer',
'drop waist',
'drop-sleeve',
'drop-waist',
'dropped',
'dye',
'dynamite',              
'eagle',
'edge',
'eiffel',
'elasticized',             
'elegant',
'elephant',
'elephant print',
'embellished',
'embroidered',
'embroidered fit',
'embroidered floral',
'embroidered gauze',    
'embroidered gauze peasant',
'embroidered lace',
'embroidered maxi',
'embroidered mesh',
'embroidered peasant',     
'embroidered shift',
'embroidered woven',
'embroidery',
'enchanted',
'ethereal',
'everyday',
'eyelash',
'eyelash knit',
'eyelash lace',
'eyelet',
'eyelet fit',
'faded',
'fair',
'fair isle',
'fan',
'fancy',
'faux',
'faux fur',
'faux leather',
'faux leather mini',
'faux leather moto',
'faux leather paneled',
'faux leather pencil',
'faux leather skater',
'faux leather varsity',
'faux leather-paneled',
'faux leather-trimmed',
'faux shearling',
'faux suede',
'faux-wrap',
'feather',
'festive',
'field',
'fisherman',
'fit',
'fit flare',
'fit skinny',
'fitted',
'fitted v-neck',
'flare',
'flared',
'flat',
'flat front',
'flat-front',
'flawless',
'flirty',                 
'floral',
'floral flutter',       
'floral knit',
'floral lace',
'floral lace mini',
'floral lace sheath',
'floral lace skater',
'floral maxi',
'floral mesh',
'floral midi',
'floral mini',
'floral paisley',               
'floral pattern',
'floral peasant',
'floral pleated',
'floral print',
'floral print skater',
'floral print strapless',
'floral print surplice',
'floral shift',
'floral skater',
'floral surplice',
'floral textured',
'floral-embroidered',
'flounce',        
'flounce maxi',
'flounced',
'flower',
'flowy',                   
'floyd',
'fluted',
'flutter',
'flutter sleeve',
'flutter-sleeve',
'foil',
'fold-over',
'foldover',
'folk',                 
'folk print',
'foulard',        
'fox',
'france',
'frayed',
'free spirit',
'french',
'french terry',
'fresh',
'frida',                       
'fringe',
'fringed',
'fur',
'fuzzy',
'fuzzy knit',
'galaxy',
'garden',
'garden party',
'gathered waistline',          
'gaucho',       
'gauze',
'gauze maxi',
'gauze peasant',
'gauzy',
'gem',
'genuine',
'geo',
'geo pattern',
'geo print',
'geo stripe',
'georgette',
'gingham',
'giraffe',
'giraffe print',
'girl',
'girls',
'glass',
'glitter',
'graphic',
'graphic muscle',
'graphic racerback',   
'grid',
'grid print',
'grunge', 
'guns',
'halen',
'harem',
'heart',
'heart print',
'heat',
'heathered',
'heathered knit',
'heathered stripe',
'heathered v-neck',
'hem',
'hepburn',
'heroes',
'herringbone',
'high-low',
'high-neck',
'high-rise',
'high-rise skinny',
'high-slit',
'high-slit maxi',
'high-waist',
'high-waisted',
'hood',
'hooded',
'hooded maxi',
'hooded utility',
'houndstooth',
'ikat',
'ikat print',
'illusion',
'illusion neckline',
'inset',
'internet',
'island',
'isle',
'jacquard',
'joie',
'kahlo',
'kaleidoscope',
'kaleidoscope print',
'kangaroo',
'kangaroo pocket',
'keyhole',
'kid',
'killin',
'kiss',
'kitty',
'knee-length',
'knit',
'knit lace',
'knit longline',
'knit maxi',
'knit mini',
'knit open',
'knit pencil',
'knit pocket',
'knit raglan',
'knit shawl',
'knit skater',
'knit stripe',
'knit striped',
'knit trapeze',
'knit v-neck',
'knotted',
'kurt',
'la',
'lace',
'lace layered',
'lace maxi',
'lace mesh',
'lace midi',
'lace mini',
'lace overlay',
'lace panel',
'lace paneled',
'lace pencil',
'lace peplum',
'lace pleated',
'lace print',
'lace sheath',
'lace sheer',
'lace shift',
'lace skater',
'lace sleeve',
'lace trim',
'lace-paneled',
'lace-trim',
'lace-trimmed',
'lace-up',                      
'lacy',
'ladder-back',
'lady',
'lakers',
'lapel',
'laser',
'lattice',
'layered',
'leaf',
'leaf print',
'leather',
'leather mini',
'leather moto',
'leather paneled',
'leather pencil',
'leather peplum',
'leather quilted',
'leather skater',
'leather trimmed',
'leather varsity',
'leather-paneled',
'leather-trimmed',
'leave',
'led',
'leopard',
'leopard print',
'life',
'light',
'lightning',
'linen',
'linen-blend',
'logo',
'long sleeve',
'long-sleeve',
'long-sleeved',
'longline',
'longline shirt',
'loop',
'loose',
'loose-knit',
'lounge',
'love',
'lover',
'low-rise',
'low-rise skinny',
'loyal',
'luxe',
'm-slit',
'm-slit maxi',
'mandala',
'mandala print',
'mandarin',
'map',
'marble',
'marble print',
'marilyn',
'marilyn monroe',
'marled',
'marled stripe',
'matelot',
'maxi',
'medallion',
'medallion print',
'medium',
'meow',
'mesh',
'mesh overlay',
'mesh panel',
'mesh paneled',
'mesh racerback',
'mesh-paneled',
'mesh-trimmed',
'metallic',
'miami',
'mickey',
'mickey mouse',
'mid rise',
'mid rise skinny',
'mid-rise',
'mid-rise skinny',
'midi',
'mina',           
'mineral',
'mineral wash',
'mini',
'minnie',
'minnie mouse',
'mirrored',
'mixed',
'mixed print',
'mixed stripe',
'mob',            
'mock',
'mock neck',
'mock-neck',
'mod',      
'modernist',
'monroe',
'moon',
'morning',
'mosaic',
'mosaic print',
'moto',
'multi-stripe',
'muscle',
'muse',
'nautical',     
'nautical stripe',
'nautical striped',
'neck ribbed',
'neck skater',
'neck striped',
'neckline',
'neon',
'neoprene',     
'nets',
'netted',
'new york',
'night',
'notched collar',
'notorious',        
'ny',
'nyc',
'nylon',
'off-the-shoulder',
'oil',
'ombre',  
'one-button',
'one-shoulder',
'open-back',
'open-front',
'open-knit',
'open-shoulder',
'organza',
'origami',
'ornate',
'ornate paisley',
'ornate print',
'overlay',  
'overlay sheath',
'oversized',
'oxford',
'paint',
'paint splatter',
'painted',
'paisley',
'paisley print',
'palm',
'palm print',
'palm springs',
'palm tree',
'pan',
'panel',
'paneled',
'paradise',
'paris',
'party',
'patched',
'patchwork',
'pattern',
'patterned',
'peasant',
'pencil',
'peplum',
'perforated',    
'performance',         
'pima',                         
'pin',           
'pineapple',
'pink',
'pinstripe',                   
'pinstriped',
'pintuck',                 
'pintuck pleated',
'pintucked',
'pizza',
'pj',      
'plaid',
'plaid shirt',
'please',
'pleat',
'pleated',
'pleated skater',
'pleated woven',
'pocket',
'pointelle',
'polka dot',
'polo',
'pom-pom',
'ponte',
'popcorn',
'popover',
'posh',
'power',
'print',
'print racerback',
'print satin',
'print scuba',
'print shift',
'print shirt',
'print skater',
'print smock',
'print smocked',
'print strapless',
'print strappy',
'print surplice',
'print tulip',
'print v-neck',
'print woven',
'printed',
'puffer',
'pullover',
'purl',
'quilted',       
'quirky',
'racerback',
'rad',
'raga',
'raglan',
'raglan sleeve',
'rainbow',
'raw',
'raw-cut',
'rebel',
'red',
'refined',
'regime',
'relaxed',
'retro',
'reverse',
'reversible',
'rhinestone',
'rib',
'rib-knit',
'ribbed',
'ribbed stripe',
'ribbed-knit',
'ringer',
'ripped',
'rise',
'rise skinny',
'roll',
'rolling',
'rolling stones',
'roman',
'rose',
'rose skater',
'roses',
'round',
'ruched',
'ruffle',
'ruffle trim',
'ruffled',
'rugby',
'rugby stripe',
'rugby striped',
'run',
'running',
'rustic',
'safari',
'sateen',
'satin',
'scallop',
'scalloped',
'scoop',
'scoop-neck',
'scuba',
'scuba skater',
'sea',
'seam',
'seamless',
'seaside',
'seersucker',
'self-tie',  
'semi-sheer',
'sequin',
'sequined',
'shaggy',
'shark',
'shawl',             
'shearling',
'sheath',
'sheer',         
'sheer-paneled',
'shift',
'shirred',
'shirt',
'shopping',
'shore',
'shoulder',
'shredded',
'side slit',
'side-slit',
'single-button',
'skater',
'skinny',
'skinny stretch',
'skort',
'sky',
'sleek',
'sleeve',
'sleeveless',
'slick',                   
'slim',
'slip',
'slit',
'slouchy',      
'slub',
'slub-knit',
'smart',
'smile',
'smock',
'smocked',
'snap',
'snoopy',
'soft',
'solid',
'sophisticated',
'southwestern',
'southwestern-inspired',
'southwestern-patterned',
'southwestern-print',
'sparkling',
'speckled',
'spirit',
'splatter',
'split',
'split-back',
'split-neck',
'spongebob',
'sporty',
'spotted',
'springs',
'square',
'standout',
'star',
'stars',
'stone',
'stone washed',
'stones',
'straight-leg',
'strap',
'strapless',
'strapless tribal',
'strappy',
'stretch',
'stretch-knit',
'stripe',
'striped',
'striped trapeze',
'striped v-neck',
'stripes',
'structured',
'studded',
'studio',
'suede',
'summer',
'sun',
'sunburst',
'sunflower',
'surfer',
'surplice',
'suspender',
'sweet',
'sweetheart',
'swim',
'swing',
'swiss',
't-back',
'taco',
'tapestry',
'tartan',
'tasmanian',
'tassel',
'tasseled',
'terry',
'texas',
'textured',
'textured woven',
'thermal',
'tie-back',
'tie-dye',
'tie-front',
'tie-neck',
'tiered',
'tile',
'toggle',
'tokyo',
'tonal',
'topstitched',
'tower',
'track',
'training',
'trapeze',
'tree',
'trench',                       
'triangle',
'tribal',
'tribal-inspired',
'trim',
'trimmed',
'tropical',
'trouble',
'trouser',
'tube',
'tulip',
'tulip-back',
'tulle',
'tunic',
'tupac',
'turtle-neck',
'tweed',
'twill',
'twist-front',
'twisted',
'two-button',
'two-tone',
'utility',
'v-back',
'v-cut',
'v-neck',
'van',
'varsity',
'varsity-striped',
'velvet',
'velveteen',
'venice',
'vent',
'vented hem',
'vertical',
'voyager',
'waffle',       
'wake',
'wash',
'washed',
'watercolor',
'wave',
'weekend',
'west',
'wide-leg',
'wifey',
'wild',
'wildflower',
'windbreaker',
'windowpane',
'woke',
'workout',
'woven',
'wrap',
'y-back',
'yoga',
'yoke',
'york',
'youth',
'zeppelin',
'zig',
'zigzag',
'zip',
'zip-front',
'zip-pocket',
'zip-up',
'zipped',
'zipper',
'zippered',
]

def draw_landmarks_cv2(cv_image, landmarks, radius=3, color=(0, 0, 255)): # BGR color for red
    """Draws landmarks on an OpenCV image (numpy array)."""
    for x, y in landmarks:
        # Ensure coordinates are within image bounds for drawing
        x_draw, y_draw = int(round(x)), int(round(y))
        # Draw a circle for each landmark
        cv2.circle(cv_image, (x_draw, y_draw), radius, color, -1) # -1 thickness fills the circle
    return cv_image


def load_model(onnx_path):
    """Load the ONNX model"""
    session = ort.InferenceSession(onnx_path)
    print("Model loaded successfully.")
    return session

def preprocess_image(image_path, input_shape):
    """Preprocess image to fit model input shape"""
    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Optional: if model expects RGB
    img_resized = cv2.resize(img, (input_shape[3], input_shape[2]))
    img_normalized = img_resized.astype(np.float32) / 255.0
    img_transposed = np.transpose(img_normalized, (2, 0, 1))  # HWC to CHW
    img_batch = np.expand_dims(img_transposed, axis=0)  # Add batch dimension
    return img_batch, img.shape

def run_inference(session, input_tensor):
    """Run inference and return output"""
    input_name = session.get_inputs()[0].name
    outputs = session.run(None, {input_name: input_tensor, 'landmarks': np.zeros((1, 16), dtype=np.float32)})  # Dummy landmarks
    return outputs[0]

def scale_landmarks(landmarks_norm, landmark_model_size, crop_size):
    # landmarks_norm: list of [x, y] normalized to landmark_model_size (e.g., 0-224)
    # landmark_model_size: (height, width) of the landmark model input
    # crop_size: (width, height) of the actual cropped image fed to landmark model
    # crop_origin_buffered: (x1, y1) of the crop in the original image (with buffer)

    lm_h, lm_w = landmark_model_size
    crop_w, crop_h = crop_size

    scaled_landmarks = []
    for lx_norm, ly_norm in landmarks_norm:
        # Scale from landmark model input space (e.g., 224x224) to crop space
        Lx_orig = int(round(lx_norm * crop_w / lm_w))
        Ly_orig = int(round(ly_norm * crop_h / lm_h))
        scaled_landmarks.append([Lx_orig, Ly_orig])

    return scaled_landmarks

if __name__ == "__main__":

    session = load_model(onnx_model_path)

    # Get input shape (e.g., (1, 3, 224, 224))
    input_shape = session.get_inputs()[0].shape
    input_tensor, img_shape = preprocess_image(image_path, input_shape)

    output = run_inference(session, input_tensor)
    
    '''
    landmarks = scale_landmarks(output, (input_shape[2], input_shape[3]), (img_shape[0], img_shape[1]))
    draw = draw_landmarks_cv2(cv2.imread(image_path), landmarks)  # Draw landmarks on the image
    cv2.imshow("Landmarks", draw)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    print("Inference Output:", output)
    '''
    ATTRIBUTE_THRESHOLD = 0.1
    attr_probs = np.array(output)  # Ensure it's a NumPy array
    mask = attr_probs >= ATTRIBUTE_THRESHOLD
    predicted_attributes = list(map(str, np.array(ATTRIBUTE_LIST_COARSE)[mask]))
    print("Inference Output:", predicted_attributes)
